global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'order-api'
    static_configs:
      - targets: ['order-api:8080']
    metrics_path: '/metrics'

  - job_name: 'payment-worker'
    static_configs:
      - targets: ['payment-worker:8081']
    metrics_path: '/metrics'
